apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:15.0
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "pg#123"
            - name: POSTGRES_USER
              value: "kubenews"
            - name: POSTGRES_DB
              value: "kubenews"
---
apiVersion: v1
kind: Service
metadata:
  name: postgre-cluster-ip
spec:
  selector:
    app: postgre
  ports:
    - port: 5432
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: web-server
          image: danbcs/kube-news:latest
          ports:
            - containerPort: 8090
          env:
            - name: DB_DATABASE
              value: "kubenews"
            - name: DB_USERNAME
              value: "kubenews"
            - name: DB_PASSWORD
              value: "pg#123"
            - name: DB_HOST
              value: "postgre"
          command: ["/bin/sh", "-ec", "sleep 50"]
---
apiVersion: v1
kind: Service
metadata:
  name: web-load-balancer
spec:
  selector:
    app: web-server
  ports:
    - port: 80
      targetPort: 8090
  type: LoadBalancer